name: Docker Image Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Private Actions Checkout
      uses: actions/checkout@v2.3.4
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        platforms: linux/arm64,linux/amd64
        file: docker/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/kafka-map:latest
